/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: broker.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "broker.pb-c.h"
void   broker__broker_payload__init
                     (Broker__BrokerPayload         *message)
{
  static const Broker__BrokerPayload init_value = BROKER__BROKER_PAYLOAD__INIT;
  *message = init_value;
}
size_t broker__broker_payload__get_packed_size
                     (const Broker__BrokerPayload *message)
{
  assert(message->base.descriptor == &broker__broker_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t broker__broker_payload__pack
                     (const Broker__BrokerPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &broker__broker_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t broker__broker_payload__pack_to_buffer
                     (const Broker__BrokerPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &broker__broker_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Broker__BrokerPayload *
       broker__broker_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Broker__BrokerPayload *)
     protobuf_c_message_unpack (&broker__broker_payload__descriptor,
                                allocator, len, data);
}
void   broker__broker_payload__free_unpacked
                     (Broker__BrokerPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &broker__broker_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor broker__broker_payload__field_descriptors[10] =
{
  {
    "handler_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, handler_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, sender_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "topic",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, topic),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, payload),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "origin_broker_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, origin_broker_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_uuid",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, message_uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transfer_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, transfer_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_number",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, sequence_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_count",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, sequence_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_data",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Broker__BrokerPayload, raw_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned broker__broker_payload__field_indices_by_name[] = {
  0,   /* field[0] = handler_key */
  5,   /* field[5] = message_uuid */
  4,   /* field[4] = origin_broker_id */
  3,   /* field[3] = payload */
  9,   /* field[9] = raw_data */
  1,   /* field[1] = sender_id */
  8,   /* field[8] = sequence_count */
  7,   /* field[7] = sequence_number */
  2,   /* field[2] = topic */
  6,   /* field[6] = transfer_id */
};
static const ProtobufCIntRange broker__broker_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor broker__broker_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "broker.BrokerPayload",
  "BrokerPayload",
  "Broker__BrokerPayload",
  "broker",
  sizeof(Broker__BrokerPayload),
  10,
  broker__broker_payload__field_descriptors,
  broker__broker_payload__field_indices_by_name,
  1,  broker__broker_payload__number_ranges,
  (ProtobufCMessageInit) broker__broker_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor broker__broker_service__method_descriptors[1] =
{
  { "MessageStream", &broker__broker_payload__descriptor, &broker__broker_payload__descriptor },
};
const unsigned broker__broker_service__method_indices_by_name[] = {
  0         /* MessageStream */
};
const ProtobufCServiceDescriptor broker__broker_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "broker.BrokerService",
  "BrokerService",
  "Broker__BrokerService",
  "broker",
  1,
  broker__broker_service__method_descriptors,
  broker__broker_service__method_indices_by_name
};
void broker__broker_service__message_stream(ProtobufCService *service,
                                            const Broker__BrokerPayload *input,
                                            Broker__BrokerPayload_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &broker__broker_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void broker__broker_service__init (Broker__BrokerService_Service *service,
                                   Broker__BrokerService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &broker__broker_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
