/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: broker.proto */

#ifndef PROTOBUF_C_broker_2eproto__INCLUDED
#define PROTOBUF_C_broker_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/any.pb-c.h"

typedef struct _Broker__BrokerPayload Broker__BrokerPayload;


/* --- enums --- */


/* --- messages --- */

struct  _Broker__BrokerPayload
{
  ProtobufCMessage base;
  char *handler_key;
  char *sender_id;
  char *topic;
  Google__Protobuf__Any *payload;
  char *origin_broker_id;
  char *message_uuid;
  char *transfer_id;
  int32_t sequence_number;
  int32_t sequence_count;
  ProtobufCBinaryData raw_data;
};
#define BROKER__BROKER_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&broker__broker_payload__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, {0,NULL} }


/* Broker__BrokerPayload methods */
void   broker__broker_payload__init
                     (Broker__BrokerPayload         *message);
size_t broker__broker_payload__get_packed_size
                     (const Broker__BrokerPayload   *message);
size_t broker__broker_payload__pack
                     (const Broker__BrokerPayload   *message,
                      uint8_t             *out);
size_t broker__broker_payload__pack_to_buffer
                     (const Broker__BrokerPayload   *message,
                      ProtobufCBuffer     *buffer);
Broker__BrokerPayload *
       broker__broker_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   broker__broker_payload__free_unpacked
                     (Broker__BrokerPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Broker__BrokerPayload_Closure)
                 (const Broker__BrokerPayload *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Broker__BrokerService_Service Broker__BrokerService_Service;
struct _Broker__BrokerService_Service
{
  ProtobufCService base;
  void (*message_stream)(Broker__BrokerService_Service *service,
                         const Broker__BrokerPayload *input,
                         Broker__BrokerPayload_Closure closure,
                         void *closure_data);
};
typedef void (*Broker__BrokerService_ServiceDestroy)(Broker__BrokerService_Service *);
void broker__broker_service__init (Broker__BrokerService_Service *service,
                                   Broker__BrokerService_ServiceDestroy destroy);
#define BROKER__BROKER_SERVICE__BASE_INIT \
    { &broker__broker_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define BROKER__BROKER_SERVICE__INIT(function_prefix__) \
    { BROKER__BROKER_SERVICE__BASE_INIT,\
      function_prefix__ ## message_stream  }
void broker__broker_service__message_stream(ProtobufCService *service,
                                            const Broker__BrokerPayload *input,
                                            Broker__BrokerPayload_Closure closure,
                                            void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor broker__broker_payload__descriptor;
extern const ProtobufCServiceDescriptor broker__broker_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_broker_2eproto__INCLUDED */
