/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: update.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "update.pb-c.h"
void   communication__update__init
                     (Communication__Update         *message)
{
  static const Communication__Update init_value = COMMUNICATION__UPDATE__INIT;
  *message = init_value;
}
size_t communication__update__get_packed_size
                     (const Communication__Update *message)
{
  assert(message->base.descriptor == &communication__update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t communication__update__pack
                     (const Communication__Update *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &communication__update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t communication__update__pack_to_buffer
                     (const Communication__Update *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &communication__update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Communication__Update *
       communication__update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Communication__Update *)
     protobuf_c_message_unpack (&communication__update__descriptor,
                                allocator, len, data);
}
void   communication__update__free_unpacked
                     (Communication__Update *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &communication__update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor communication__update__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Communication__Update, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Communication__Update, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_utc",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Communication__Update, timestamp_utc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned communication__update__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = message */
  2,   /* field[2] = timestamp_utc */
};
static const ProtobufCIntRange communication__update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor communication__update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "communication.Update",
  "Update",
  "Communication__Update",
  "communication",
  sizeof(Communication__Update),
  3,
  communication__update__field_descriptors,
  communication__update__field_indices_by_name,
  1,  communication__update__number_ranges,
  (ProtobufCMessageInit) communication__update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
