/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: update.proto */

#ifndef PROTOBUF_C_update_2eproto__INCLUDED
#define PROTOBUF_C_update_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Communication__Update Communication__Update;


/* --- enums --- */


/* --- messages --- */

struct  _Communication__Update
{
  ProtobufCMessage base;
  char *id;
  char *message;
  int64_t timestamp_utc;
};
#define COMMUNICATION__UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&communication__update__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/* Communication__Update methods */
void   communication__update__init
                     (Communication__Update         *message);
size_t communication__update__get_packed_size
                     (const Communication__Update   *message);
size_t communication__update__pack
                     (const Communication__Update   *message,
                      uint8_t             *out);
size_t communication__update__pack_to_buffer
                     (const Communication__Update   *message,
                      ProtobufCBuffer     *buffer);
Communication__Update *
       communication__update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   communication__update__free_unpacked
                     (Communication__Update *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Communication__Update_Closure)
                 (const Communication__Update *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor communication__update__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_update_2eproto__INCLUDED */
